use clap::ValueEnum;

#[derive(Debug, Clone, Copy, ValueEnum, PartialEq, Eq)]
pub(crate) enum ScanProfile {
    Deep,
    Balanced,
    Passive,
    Turbo,
}

#[derive(Debug, Clone, Copy)]
pub(crate) struct ProfileDefaults {
    pub(crate) max_runtime: u64,
    pub(crate) max_words: usize,
    pub(crate) active_max_runtime: u64,
    pub(crate) max_passive: usize,
    pub(crate) depth: usize,
    pub(crate) recursive_words: usize,
    pub(crate) recursive_hosts: usize,
    pub(crate) pipeline_rounds: usize,
    pub(crate) pipeline_budget: usize,
    pub(crate) tls_hosts: usize,
    pub(crate) graph_hosts: usize,
    pub(crate) ptr_ips: usize,
    pub(crate) internetdb_ips: usize,
    pub(crate) internetdb_max_runtime: u64,
    pub(crate) nsec_max_names: usize,
    pub(crate) nsec_max_runtime: u64,
    pub(crate) ct_logs: usize,
    pub(crate) ct_entries: usize,
    pub(crate) ct_backfill: usize,
    pub(crate) ct_max_runtime: u64,
    pub(crate) web_hosts: usize,
    pub(crate) web_max_runtime: u64,
    pub(crate) web_assets: usize,
    pub(crate) passive_max_runtime: u64,
    pub(crate) passive_zone_concurrency: usize,
}

impl ScanProfile {
    pub(crate) const fn defaults(self) -> ProfileDefaults {
        match self {
            Self::Deep => ProfileDefaults {
                max_runtime: 0,
                max_words: 1_000_000,
                active_max_runtime: 0,
                max_passive: 25_000,
                depth: 5,
                recursive_words: 1_000,
                recursive_hosts: 1_000,
                pipeline_rounds: 10,
                pipeline_budget: 0,
                tls_hosts: 250,
                graph_hosts: 1_000,
                ptr_ips: 512,
                internetdb_ips: 16,
                internetdb_max_runtime: 0,
                nsec_max_names: 10_000,
                nsec_max_runtime: 0,
                ct_logs: 8,
                ct_entries: 4_096,
                ct_backfill: 4_096,
                ct_max_runtime: 0,
                web_hosts: 100,
                web_max_runtime: 0,
                web_assets: 8,
                passive_max_runtime: 0,
                passive_zone_concurrency: 4,
            },
            Self::Balanced => ProfileDefaults {
                max_runtime: 0,
                max_words: 5_000,
                active_max_runtime: 0,
                max_passive: 10_000,
                depth: 3,
                recursive_words: 100,
                recursive_hosts: 50,
                pipeline_rounds: 2,
                pipeline_budget: 0,
                tls_hosts: 100,
                graph_hosts: 250,
                ptr_ips: 64,
                internetdb_ips: 8,
                internetdb_max_runtime: 0,
                nsec_max_names: 10_000,
                nsec_max_runtime: 0,
                ct_logs: 2,
                ct_entries: 256,
                ct_backfill: 256,
                ct_max_runtime: 0,
                web_hosts: 30,
                web_max_runtime: 0,
                web_assets: 5,
                passive_max_runtime: 0,
                passive_zone_concurrency: 4,
            },
            Self::Passive => ProfileDefaults {
                max_runtime: 0,
                max_words: 0,
                active_max_runtime: 0,
                max_passive: 250_000,
                depth: 1,
                recursive_words: 1,
                recursive_hosts: 1,
                pipeline_rounds: 1,
                pipeline_budget: 0,
                tls_hosts: 1,
                graph_hosts: 1,
                ptr_ips: 1,
                internetdb_ips: 1,
                internetdb_max_runtime: 0,
                nsec_max_names: 1,
                nsec_max_runtime: 0,
                ct_logs: 8,
                ct_entries: 4_096,
                ct_backfill: 4_096,
                ct_max_runtime: 0,
                web_hosts: 1,
                web_max_runtime: 0,
                web_assets: 1,
                passive_max_runtime: 0,
                passive_zone_concurrency: 6,
            },
            Self::Turbo => ProfileDefaults {
                max_runtime: 0,
                max_words: 1_000_000,
                active_max_runtime: 0,
                max_passive: 50_000,
                depth: 3,
                recursive_words: 1_000,
                recursive_hosts: 1_000,
                pipeline_rounds: 4,
                pipeline_budget: 0,
                tls_hosts: 100,
                graph_hosts: 500,
                ptr_ips: 128,
                internetdb_ips: 4,
                internetdb_max_runtime: 0,
                nsec_max_names: 10_000,
                nsec_max_runtime: 0,
                ct_logs: 2,
                ct_entries: 512,
                ct_backfill: 512,
                ct_max_runtime: 0,
                web_hosts: 50,
                web_max_runtime: 0,
                web_assets: 5,
                passive_max_runtime: 0,
                passive_zone_concurrency: 8,
            },
        }
    }
}
