use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PassiveSourceOutcome {
    Success,
    Cached,
    Partial,
    Deferred,
    Skipped,
    Stale,
}

#[derive(Debug, Clone)]
pub enum ProgressEvent {
    Started {
        scan_id: i64,
        domain: String,
    },
    Phase {
        name: String,
        detail: String,
    },
    PassiveSource {
        source: String,
        outcome: PassiveSourceOutcome,
        status: String,
        names: usize,
    },
    AxfrAttempt(crate::model::AxfrAttempt),
    TlsCertificates {
        endpoints: usize,
        network: usize,
        successes: usize,
        failures: usize,
        cache_hits: usize,
        names: usize,
        duration_ms: u128,
    },
    DnsGraph {
        queries: usize,
        edges: usize,
        names: usize,
        child_zones: usize,
        services: usize,
        duration_ms: u128,
    },
    WebDiscovery {
        hosts: usize,
        requests: usize,
        cache_hits: usize,
        failures: usize,
        names: usize,
        duration_ms: u128,
    },
    Dnssec {
        zones: usize,
        walked: usize,
        protected: usize,
        queries: usize,
        names: usize,
    },
    CtMonitor {
        logs: usize,
        entries: usize,
        failures: usize,
        names: usize,
        duration_ms: u128,
    },
    DnsProgress {
        phase: String,
        processed: usize,
        total: usize,
        found: usize,
        cache_hits: usize,
        rate: f64,
        elapsed_ms: u128,
    },
    Finding(Finding),
    Warning(String),
    Complete,
}

pub type ProgressCallback = Arc<dyn Fn(ProgressEvent) + Send + Sync>;

#[derive(Debug, Clone)]
pub struct ScanOptions {
    pub wordlist: Option<PathBuf>,
    pub mutation_rules: Vec<MutationRule>,
    pub max_words: usize,
    pub active_phase_timeout: Duration,
    pub passive: bool,
    pub passive_sources: Vec<String>,
    pub api_keys: ApiKeyStore,
    pub automatic_source_selection: bool,
    pub passive_refresh: Duration,
    pub passive_phase_timeout: Duration,
    pub passive_zone_concurrency: usize,
    pub passive_concurrency: usize,
    pub max_passive: usize,
    pub passive_only: bool,
    pub no_target_contact: bool,
    pub axfr: bool,
    pub axfr_timeout: Duration,
    pub refresh_cache: bool,
    pub verification_max_age: Duration,
    pub only_live: bool,
    pub profile: String,
    pub checkpoint_every: Duration,
    pub resume: Option<String>,
    pub ttl_cap: u32,
    pub negative_ttl: u32,
    pub include_wildcard: bool,
    pub wildcard_refresh: Duration,
    pub recursive_depth: usize,
    pub recursive_words: usize,
    pub recursive_hosts: usize,
    pub adaptive: bool,
    pub pipeline: bool,
    pub pipeline_rounds: usize,
    pub pipeline_budget: usize,
    pub tls_certificates: bool,
    pub tls_port: u16,
    pub tls_timeout: Duration,
    pub tls_refresh: Duration,
    pub tls_max_hosts: usize,
    pub tls_concurrency: usize,
    pub dns_graph: bool,
    pub graph_max_hosts: usize,
    pub service_discovery: bool,
    pub ptr_pivot: bool,
    pub ptr_max_ips: usize,
    pub internetdb_pivot: bool,
    pub internetdb_max_ips: usize,
    pub internetdb_phase_timeout: Duration,
    pub internetdb_refresh: Duration,
    pub dnssec_nsec: bool,
    pub nsec_timeout: Duration,
    pub nsec_refresh: Duration,
    pub nsec_max_names: usize,
    pub nsec_phase_timeout: Duration,
    pub ct_monitor: bool,
    pub ct_timeout: Duration,
    pub ct_phase_timeout: Duration,
    pub ct_max_logs: usize,
    pub ct_entries_per_log: usize,
    pub ct_initial_backfill: usize,
    pub metadata_discovery: bool,
    pub metadata_all_hosts: bool,
    pub metadata_max_requests: usize,
    pub web_discovery: bool,
    pub web_max_hosts: usize,
    pub web_timeout: Duration,
    pub web_phase_timeout: Duration,
    pub web_refresh: Duration,
    pub web_concurrency: usize,
    pub web_max_bytes: usize,
    pub web_assets_per_host: usize,
}
